version: '3'

services:
  db:
    platform: linux/amd64
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on: 
      - db 
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel: